info: # SERVER
  description: Measurement for WP5 Reindeer Exp. 4aa PART 1
  exp_name: phase_75 #4aa-part-1
  server_user_name: jarne
  ip: 10.128.48.3
  port: 5558 # EXTERNAL CONTROL
control:
  transmission: auto # external
  duration: 20
ansible: # SERVER
  inventory: hosts.yaml
  copy_client_script: copy_client_script.yaml
  start_client_script: start_client_script.yaml
  # stop_client_script:
# usrp:
client: # CLIENT
  enable_client_script: true
  tiles: multiON # Define tiles that should be accessed by ansible
  script: tx_waveforms_random_phase.py # ENSURE script is under folder *** <<ROOT-EXP>>/client/<<NAME>>.py ***
  # ansibletiles: segmentA
  ip: 192.108.0.204 #10.128.48.3 #192.108.0.204
  hosts:
    all:
      freq: 920000000.0
      gain: 75
      channels: [0, 1]
      duration: 10 #3600
    # T04: 
    #   gain: 30
positioning: # MEASUREMENT EQUIPMENT
  enabled: true
  ip: 192.108.0.13
  protocol: zmq
  port: 5555
  system: QUALYSIS
  xaxisoffset: 0
  yaxisoffset: 0
  zaxisoffset: 0
  csv_header: ['x', 'y', 'z', 'utc','rm']
scope: # MEASUREMENT EQUIPMENT
  enabled: true
  cable_loss: 10
  bandwidth_hz: 6E9
  center_hz: 920000000.0
  ip: 192.108.0.251
  rbw_hz: 100.0
  span_hz: 10000.0
  csv_header: ['dbm']
ep: # MEASUREMENT EQUIPMENT
  enabled: true
  ip: 192.108.0.13
  protocol: zmq
  port: 5556
  csv_header: ['buffer_voltage_mv', 'resistance', 'pwr_nw']