info: # SERVER
  description: Measurement for WP5 Reindeer Exp. 4aa PART 1
  exp_name: 4aa-part-1
  server_user_name: jarne
  ip: 'localhost'
  port: 5558 # EXTERNAL CONTROL
ansible: # SERVER
  inventory: hosts.yaml
  copy_client_script: copy_client_script.yaml
  start_client_script: start_client_script.yaml
  # stop_client_script:
# usrp:
client: # CLIENT
  enable_client_script: true
  tiles: multiON # Define tiles that should be accessed by ansible
  script: tx_waveforms_random_phase.py # ENSURE script is under folder *** <<ROOT-EXP>>/client/<<NAME>>.py ***
  # ansibletiles: segmentA
  hosts:
    all:
      freq: 917000000.0
      gain: 50
    T04: 
      gain: 30
positioning: # MEASUREMENT EQUIPMENT
  ip: 192.108.0.13
  protocol: zmq
  port: 5555S
  system: QUALYSIS
  xaxisoffset: 0
  yaxisoffset: 0
  zaxisoffset: 0
  csv_header: ['x', 'y', 'z', 'utc']
scope: # MEASUREMENT EQUIPMENT
  cable_loss: 0
  center_Hz: 5850000000.0
  ip: 192.108.0.251
  rbw_Hz: 100.0
  span_Hz: 10000000.0
  csv_header: ['dbm']
ep: # MEASUREMENT EQUIPMENT
  ip: 192.108.0.13
  protocol: zmq
  port: 5556
  csv_header: ['buffer_voltage_mv', 'resistance', 'pwr_nw']