info: # SERVER
  description: Measurement for WP5 Reindeer Exp. 4aa PART 1
  exp_name: 4aa-part-1
  server_user_name: jarne
ansible: # SERVER
  # tiles: multiON # Define tiles that should be accessed by ansible
  inventory: hosts.yaml
  copy_client_script: copy_client_script.yaml
  start_client_script: start_transmitters_random_phase.yaml
  # stop_client_script:
positioning: # MEASUREMENT EQUIPMENT
  ip: 192.108.0.13
  system: QUALYSIS
  xaxisoffset: 0
  yaxisoffset: 0
  zaxisoffset: 0
scope: # MEASUREMENT EQUIPMENT
  cable_loss: 0
  center_Hz: 5850000000.0
  ip: 192.108.0.251
  rbw_Hz: 100.0
  span_Hz: 10000000.0
# usrp:
client: # CLIENT
  tiles: multiON # Define tiles that should be accessed by ansible
  script: tx_waveforms_random_phase.py
  # ansibletiles: segmentA
  transmitters_enabled: true
  hosts:
    all:
      freq: 917000000.0
      gain: 50
    T04: 
      gain: 30

