RX_TX_SAME_CHANNEL: !!bool False  # if loopback is done from one channel to the other channel
CLOCK_TIMEOUT: !!float 1000  # 1000mS timeout for external clock locking
INIT_DELAY: !!float 0.2  # 200ms initial delay before transmit
RATE: !!float 1e6

LOOPBACK_TX_GAIN: !!float 62 #70  # empirical determined
LOOPBACK_RX_GAIN: !!float 34 #23  # empirical determined
REF_RX_GAIN: !!float 30 #28  # empirical determined
FREQ: !!float 920e6


CAPTURE_TIME: !!float 5

server_ip: "10.128.52.53"