RX_TX_SAME_CHANNEL: !!bool False  # if loopback is done from one channel to the other channel
CLOCK_TIMEOUT: !!float 1000  # 1000mS timeout for external clock locking
INIT_DELAY: !!float 0.2  # 200ms initial delay before transmit
RATE: !!int 250e3
CAPTURE_TIME: !!float 4
LOOPBACK_TX_GAIN: !!float 70  # emperical determined
LOOPBACK_RX_GAIN: !!float 23  # emperical determined
REF_RX_GAIN: !!float 28  # emperical determined