---
- name: Start PILOT USRP
  hosts: PILOT
  gather_facts: no
  serial: 0
  environment:
    PYTHONPATH: "/usr/local/lib/python3/dist-packages"
    UHD_IMAGES_DIR: "/usr/share/uhd/images" # no idea why we need to include this as it is defined .bashrc
  vars_files:
    - vars.yml  # Import the variable file
  tasks:
    - name: "Reset GIT to be sure"
      shell: "git fetch origin && git reset --hard origin/main"
      args:
        chdir: ~/experiments/
    - name: Change to experiments directory and pull latest code from git
      shell: "git pull"
      args:
        chdir: ~/experiments/
    - name: Kill the background script process
      shell: "sudo ps aux | grep usrp-pilot | grep -v grep | awk '{print $2}' | xargs -r kill -9"
      ignore_errors: yes
    - name: Kill the process listening on 0.0.0.0:50001
      shell: "sudo netstat -ltnp | grep '0.0.0.0:50001' | awk '{print $7}' | cut -d'/' -f1 | xargs -r sudo kill -9"
      ignore_errors: yes  # Ignore errors in case no process is found
    - name: chmod +x to be sure
      ansible.builtin.shell:
        cmd: "chmod +x usrp-pilot.sh"
        chdir: ~/experiments/02_reciprocity_based_WPT/client
    - name: remove windows errors 
      ansible.builtin.shell:
        cmd: sed -i -e 's/\r$//' ./usrp-pilot.sh
        chdir: ~/experiments/02_reciprocity_based_WPT/client
    - name: Start PILOT
      ansible.builtin.shell:
        cmd: nohup ./usrp-pilot.sh --ip {{ server_ip }} > log.txt 2>&1 &
        chdir: ~/experiments/02_reciprocity_based_WPT/client
        executable: /bin/bash
     