---
- name: Start PILOT USRP
  hosts: PILOT
  gather_facts: no
  serial: 0
  environment:
    PYTHONPATH: "/usr/local/lib/python3/dist-packages"
    UHD_IMAGES_DIR: "/usr/share/uhd/images" # no idea why we need to include this as it is defined .bashrc
  tasks:
    - name: Change to experiments directory and pull latest code from git
      shell: "git pull"
      args:
        chdir: ~/experiments/
    - name: Kill the background script process
      shell: "ps aux | grep usrp-pilot.sh | grep -v grep | awk '{print $2}' | xargs kill -9"
      ignore_errors: yes
      become: yes
      become_method: sudo
    - name: Kill the process listening on 0.0.0.0:50001
      shell: "sudo kill -9 $(sudo netstat -ltnp | grep '0.0.0.0:50001' | awk '{print $7}' | cut -d'/' -f1)"
      ignore_errors: yes  # Ignore errors in case no process is found
    - name: Start PILOT
      ansible.builtin.shell:
        cmd: nohup ./usrp-pilot.sh > log.txt 2>&1 &
        chdir: ~/experiments/02_reciprocity_based_WPT/client
        executable: /bin/bash
     